[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm ci && npm run build"

[deploy]
startCommand = "cd backend && python run.py"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "backend"
directory = "backend" 