[build]
builder = "nixpacks"
buildCommand = "nixpacks build . --name app"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT 'app:create_app()'"
restartPolicyType = "on_failure"
healthcheckPath = "/api/test"
healthcheckTimeout = 100

[deploy.variables]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18" 