[phases.setup]
nixPkgs = ['python39', 'nodejs@18', 'gcc']
aptPkgs = ['python3-pip']

[phases.install]
cmds = [
    'cd frontend && npm ci',
    'cd ../backend && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd frontend && npm run build',
    'cd ../backend && python -m pip install gunicorn'
]

[start]
cmd = 'cd backend && gunicorn --bind 0.0.0.0:$PORT app:create_app()' 