[phases.setup]
nixPkgs = ['python39', 'nodejs@18', 'gcc']

[phases.install]
cmds = [
    'cd frontend && npm ci',
    'cd ../backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd backend && python run.py' 