[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "gcc"
]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT run:app" 