[phases.setup]
nixPkgs = ["python39"]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install gunicorn"
]

[start]
cmd = "gunicorn 'app:create_app()' --bind 0.0.0.0:$PORT" 