[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.numpy",
    "gcc",
    "gfortran"
]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT"