[phases.setup]
nixPkgs = ["python39", "gcc"]
aptPkgs = ["python3-dev", "build-essential"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install gunicorn"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT 'app:create_app()'" 